[project]
name = "cq"
version = "0.1.1"
description = "Checks the code quality of a python file or project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diskcache>=5.6.3",
    "coverage>=7.8.2",
    "pydocstyle>=6.3.0",
    "pytest>=8.4.0",
    "radon>=6.0.1",
    "rich>=14.0.0",
    "typer>=0.16.0",
    "pytest>=8.4.0",
    "pytest-cov>=6.1.1",
    "pyyaml>=6.0.2",
    "ty>=0.0.17",
    "ruff>=0.14.1",
    "bandit>=1.8.0",
    "vulture>=2.14",
    "pytest-json-report>=1.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.scripts]
    cq = "cq.main:main"
