[project]
name = "cq"
version = "0.1.0"
description = "Checks the code quality of a file or project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachier>=3.1.2",
    "coverage>=7.8.2",
    "pydocstyle>=6.3.0",
    "pytest>=8.4.0",
    "radon>=6.0.1",
    "rich>=14.0.0",
    "typer>=0.16.0",
    "pytest>=8.4.0",
    "pytest-cov>=6.1.1",
    "numpy>=2.2.6",
    "matplotlib>=3.10.3",
    "pyyaml>=6.0.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "ruff>=0.11.12",
]

[project.scripts]
    cq = "cq.main:main"
