tools:
  compilation:
    name: "compile"
    command: "python -m compileall -r 10 -j 8 -f {context_path} -x .*venv"
    parser: "CompileParser"
    priority: 1
    warning_threshold: 0.9999
    error_threshold: 0.9999
    
  pytest:
    name: "pytest"
    command: "pytest -v {context_path}"
    parser: "PytestParser"
    priority: 2
    warning_threshold: 0.7
    error_threshold: 0.5

  coverage:
    name: "coverage"
    command: "coverage run -m pytest {context_path} && coverage report"
    parser: "CoverageParser"
    priority: 2
    warning_threshold: 0.9
    error_threshold: 0.5

  pydocstyle:
    name: "pydocstyle"
    command: "pydocstyle --convention=google {context_path}"
    parser: "PydocstyleParser"
    priority: 5
    warning_threshold: 0.8
    error_threshold: 0.3

  maintainability:
    name: "radon mi"
    command: "radon mi -s --json {context_path}"
    parser: "MaintainabilityParser"
    priority: 3
    warning_threshold: 0.6
    error_threshold: 0.4

  complexity:
    name: "radon cc"
    command: "radon cc --json {context_path}"
    parser: "ComplexityParser"
    priority: 3
    warning_threshold: 0.6
    error_threshold: 0.4

  halstead:
    name: "radon hal"
    command: "radon hal -f --json {context_path}"
    parser: "HalsteadParser"
    priority: 4
    warning_threshold: 0.5
    error_threshold: 0.3
